### ISSUE TITLE
Disable highlight for various command lines

### ISSUE THREAD

**Issue by Resike** [p3lim/sublime-highlight-trailing-whitespace#1]
Any chance you could disable the highlighting for the package control search bar, the console window and the command palette window?

**Comment by p3lim** [comment]
Please provide a screenshot of that happening.

**Comment by Resike** [comment]
![01](https://user-images.githubusercontent.com/3955703/32237535-79787e0a-be65-11e7-8b7d-610578fbe9b1.png)
![02](https://user-images.githubusercontent.com/3955703/32237536-799848c0-be65-11e7-8107-72a21e69c3b7.png)
![03](https://user-images.githubusercontent.com/3955703/32237538-79b25724-be65-11e7-89d3-f56ea4ddffb1.png)

**Comment by p3lim** [comment]
Toss me your ST settings and PackageControl list of plugins (both found in `%APPDATA%\Sublime Text 3\Packages\User`) and I'll take a swing at replicating this during the weekend, I've never seen this behavior myself.
Also, what version of ST are you using?

**Comment by Resike** [comment]
It's started when i updated to ST3 3143.

**Comment by Resike** [comment]
Also would be nice to add something like this to prevent crashing in big files:

`def highlight_whitespace(view):
	if view.size() > 1e6:
		return`

**Comment by p3lim** [comment]
I can't replicate the issue on any of the systems I have, tried both dev versions and the one you have.
Please make sure there's not a conflicting package.

**Comment by Resike** [comment]
It happes for me even on a fresh Sublime settings with only this packages:
![01](https://user-images.githubusercontent.com/3955703/32449985-4f432d3a-c313-11e7-8577-e309796c9998.png)

**Comment by randy3k** [comment]
A bug was filed in [Terminus](https://github.com/randy3k/Terminus/issues/6) related to your package.
The bug in this thread and that bug are caused by the fact that you didn't check if the view is a widget.
It would be accomplished by the setting `is_widget`, e.g.,
```
        if view.settings().get('is_widget'):
            return
```

**Comment by p3lim** [comment]
Thanks for that @randy3k.
