### ISSUE TITLE
Feature Request: Customization

### ISSUE THREAD

**Issue by NetOpWibby** [p3lim/sublime-highlight-trailing-whitespace#4]
I'd like to customize the visual indicator. Parameters could look like:

```
"highlight_trailing_whitespace_background_color": hex,
"highlight_trailing_whitespace_border_color": hex,
"highlight_trailing_whitespace_padding_direction": number
```

**Comment by p3lim** [comment]
What do you mean by padding direction?
The other two are colored based on your theme, but I'll see if there's a way to override that.

**Comment by NetOpWibby** [comment]
I'm basing this on general settings. There are parameters `line_padding_top` and `line_padding_bottom`. I figured someone would like to have specific sizing of the visual indicator.

**Comment by p3lim** [comment]
The way the outline is drawed is by manipulating the region (the space in the buffer that is rendered).
I pretty much only have access to the outline and filling the entire buffer with a single color.

I'll add an option to color the outline (hex, hex w/ alpha, RGB, RGBA, HSL, HSLA, and CSS color names), but that's pretty much what I'm able to do.

**Comment by p3lim** [comment]
Give that a go.

**Comment by p3lim** [comment]
Updated docs: https://github.com/p3lim/sublime-highlight-trailing-whitespace/commit/723c0400d87aa268b9f35da81926e701e15ff812?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by NetOpWibby** [comment]
Ah okay! Thanks for the explanation and definitely thanks for adding this! :D
